import type { EarningsRow } from "./earnings";

/**
 * Demo rows shown when no D1 binding is present (local `next dev`) or a read
 * fails. Crafted to exercise every UI path: standalone + consolidated pairs,
 * a loss->profit turnaround, a profit->loss swing, a bank with no EBITDA margin,
 * and a mix of up/down YoY & QoQ moves.
 */

const ATTACH = "https://www.bseindia.com/xml-data/corpfiling/AttachLive/";

let _id = 0;
type Seed = Partial<EarningsRow> & { company_name: string; dedup_key: string };

function mk(seed: Seed): EarningsRow {
  _id += 1;
  const base: EarningsRow = {
    id: _id,
    company_name: seed.company_name,
    bse_scrip_code: null,
    nse_symbol: null,
    result_type: "standalone",
    quarter_label: "Q1 FY27",
    period_end: "2026-06-30",
    prev_quarter_end: "2026-03-31",
    year_ago_quarter_end: "2025-06-30",
    reporting_unit: "Rs in Crore",
    revenue_cr: null,
    revenue_yoy_pct: null,
    revenue_qoq_pct: null,
    net_profit_cr: null,
    net_profit_yoy_pct: null,
    net_profit_qoq_pct: null,
    net_profit_swing: null,
    ebitda_cr: null,
    ebitda_yoy_pct: null,
    ebitda_qoq_pct: null,
    ebitda_margin_pct: null,
    ebitda_margin_yoy_pct: null,
    ebitda_margin_qoq_pct: null,
    revenue_cur_cr: null,
    revenue_prevq_cr: null,
    revenue_yrago_cr: null,
    net_profit_cur_cr: null,
    net_profit_prevq_cr: null,
    net_profit_yrago_cr: null,
    ebitda_cur_cr: null,
    ebitda_prevq_cr: null,
    ebitda_yrago_cr: null,
    exchange: "BSE",
    category: "Result",
    headline: "Financial Results for the Quarter ended June 30, 2026",
    attachment_url: ATTACH + "demo.pdf",
    source_label: "BSE Filing",
    raw_text: null,
    extraction_confidence: 0.92,
    extraction_model: "demo (mock data)",
    bse_announcement_id: null,
    dedup_key: seed.dedup_key,
    filed_at: "2026-07-28T18:42:00",
    pdf_checked: 1,
    created_at: "2026-07-28T19:00:00",
    updated_at: "2026-07-28T19:00:00",
  };
  return { ...base, ...seed };
}

export const MOCK_EARNINGS: EarningsRow[] = [
  mk({
    company_name: "Davangere Sugar Company Ltd",
    bse_scrip_code: "531055",
    nse_symbol: "DAVANGERE",
    result_type: "standalone",
    reporting_unit: "Rs. in Lakhs",
    revenue_cr: 34.72, revenue_yoy_pct: 44.2, revenue_qoq_pct: -58.6,
    net_profit_cr: 0.94, net_profit_yoy_pct: -28.0, net_profit_qoq_pct: -51.9,
    ebitda_cr: 11.16, ebitda_yoy_pct: -2.0, ebitda_qoq_pct: 32.1,
    ebitda_margin_pct: 32.14, ebitda_margin_yoy_pct: 47.30, ebitda_margin_qoq_pct: 10.08,
    revenue_cur_cr: 34.72, revenue_prevq_cr: 83.86, revenue_yrago_cr: 24.08,
    net_profit_cur_cr: 0.94, net_profit_prevq_cr: 1.95, net_profit_yrago_cr: 1.31,
    ebitda_cur_cr: 11.16, ebitda_prevq_cr: 8.45, ebitda_yrago_cr: 11.39,
    dedup_key: "MOCK0001|standalone",
    filed_at: "2026-07-28T18:42:00",
    headline: "Financial Results for the Quarter ended June 30, 2026",
  }),
  mk({
    company_name: "Meridian Software Services Ltd",
    bse_scrip_code: "532819",
    nse_symbol: "MERIDSOFT",
    result_type: "consolidated",
    revenue_cr: 1284.5, revenue_yoy_pct: 12.6, revenue_qoq_pct: 3.4,
    net_profit_cr: 212.3, net_profit_yoy_pct: 18.9, net_profit_qoq_pct: 5.1,
    ebitda_cr: 305.8, ebitda_yoy_pct: 15.2, ebitda_qoq_pct: 4.8,
    ebitda_margin_pct: 23.81, ebitda_margin_yoy_pct: 23.27, ebitda_margin_qoq_pct: 23.50,
    revenue_cur_cr: 1284.5, revenue_prevq_cr: 1242.3, revenue_yrago_cr: 1140.8,
    net_profit_cur_cr: 212.3, net_profit_prevq_cr: 201.9, net_profit_yrago_cr: 178.6,
    ebitda_cur_cr: 305.8, ebitda_prevq_cr: 291.7, ebitda_yrago_cr: 265.4,
    dedup_key: "MOCK0002|consolidated",
    filed_at: "2026-07-28T17:10:00",
    headline: "Consolidated Financial Results for the Quarter ended June 30, 2026",
  }),
  mk({
    company_name: "Meridian Software Services Ltd",
    bse_scrip_code: "532819",
    nse_symbol: "MERIDSOFT",
    result_type: "standalone",
    revenue_cr: 1102.7, revenue_yoy_pct: 11.1, revenue_qoq_pct: 2.9,
    net_profit_cr: 198.4, net_profit_yoy_pct: 17.2, net_profit_qoq_pct: 4.4,
    ebitda_cr: 268.1, ebitda_yoy_pct: 14.0, ebitda_qoq_pct: 4.1,
    ebitda_margin_pct: 24.31, ebitda_margin_yoy_pct: 23.69, ebitda_margin_qoq_pct: 24.02,
    revenue_cur_cr: 1102.7, revenue_prevq_cr: 1071.6, revenue_yrago_cr: 992.5,
    net_profit_cur_cr: 198.4, net_profit_prevq_cr: 190.0, net_profit_yrago_cr: 169.3,
    ebitda_cur_cr: 268.1, ebitda_prevq_cr: 257.5, ebitda_yrago_cr: 235.2,
    dedup_key: "MOCK0002|standalone",
    filed_at: "2026-07-28T17:10:00",
    headline: "Standalone Financial Results for the Quarter ended June 30, 2026",
  }),
  mk({
    company_name: "Konark Infra Projects Ltd",
    bse_scrip_code: "533308",
    nse_symbol: "KONARKINFRA",
    result_type: "standalone",
    reporting_unit: "INR Million",
    revenue_cr: 148.92, revenue_yoy_pct: 61.4, revenue_qoq_pct: 9.2,
    net_profit_cr: 6.35, net_profit_yoy_pct: 320.5, net_profit_qoq_pct: 254.1,
    net_profit_swing: "loss->profit",
    ebitda_cr: 18.74, ebitda_yoy_pct: 84.5, ebitda_qoq_pct: 21.7,
    ebitda_margin_pct: 12.58, ebitda_margin_yoy_pct: 11.02, ebitda_margin_qoq_pct: 11.29,
    revenue_cur_cr: 148.92, revenue_prevq_cr: 136.35, revenue_yrago_cr: 92.27,
    net_profit_cur_cr: 6.35, net_profit_prevq_cr: -4.12, net_profit_yrago_cr: -2.88,
    ebitda_cur_cr: 18.74, ebitda_prevq_cr: 15.4, ebitda_yrago_cr: 10.16,
    dedup_key: "MOCK0003|standalone",
    filed_at: "2026-07-28T16:05:00",
    extraction_confidence: 0.88,
    headline: "Un-audited Financial Results for the Quarter ended 30th June 2026",
  }),
  mk({
    company_name: "Sunrise Finance & Investments Ltd",
    bse_scrip_code: "500302",
    nse_symbol: "SUNRISEFIN",
    result_type: "standalone",
    revenue_cr: 842.1, revenue_yoy_pct: 9.8, revenue_qoq_pct: 2.1,
    net_profit_cr: 176.5, net_profit_yoy_pct: 14.3, net_profit_qoq_pct: -3.2,
    // Bank / NBFC — operating EBITDA & margin are not meaningful; stored null.
    ebitda_cr: null, ebitda_yoy_pct: null, ebitda_qoq_pct: null,
    ebitda_margin_pct: null, ebitda_margin_yoy_pct: null, ebitda_margin_qoq_pct: null,
    revenue_cur_cr: 842.1, revenue_prevq_cr: 824.8, revenue_yrago_cr: 766.9,
    net_profit_cur_cr: 176.5, net_profit_prevq_cr: 182.3, net_profit_yrago_cr: 154.4,
    ebitda_cur_cr: null, ebitda_prevq_cr: null, ebitda_yrago_cr: null,
    dedup_key: "MOCK0004|standalone",
    filed_at: "2026-07-27T19:30:00",
    reporting_unit: "Rs in Crore",
    headline: "Financial Results for the Quarter ended June 30, 2026 (NBFC)",
  }),
  mk({
    company_name: "Aurora Pharma Laboratories Ltd",
    bse_scrip_code: "524804",
    nse_symbol: "AURORAPHAR",
    result_type: "consolidated",
    revenue_cr: 496.8, revenue_yoy_pct: 27.4, revenue_qoq_pct: 8.9,
    net_profit_cr: 74.2, net_profit_yoy_pct: 41.6, net_profit_qoq_pct: 12.3,
    ebitda_cr: 128.5, ebitda_yoy_pct: 33.8, ebitda_qoq_pct: 10.1,
    ebitda_margin_pct: 25.87, ebitda_margin_yoy_pct: 24.63, ebitda_margin_qoq_pct: 25.58,
    revenue_cur_cr: 496.8, revenue_prevq_cr: 456.2, revenue_yrago_cr: 390.0,
    net_profit_cur_cr: 74.2, net_profit_prevq_cr: 66.1, net_profit_yrago_cr: 52.4,
    ebitda_cur_cr: 128.5, ebitda_prevq_cr: 116.7, ebitda_yrago_cr: 96.0,
    dedup_key: "MOCK0005|consolidated",
    filed_at: "2026-07-27T18:15:00",
    headline: "Consolidated Financial Results for the Quarter ended June 30, 2026",
  }),
  mk({
    company_name: "Titan Steelworks Ltd",
    bse_scrip_code: "513375",
    nse_symbol: "TITANSTEEL",
    result_type: "standalone",
    revenue_cr: 612.4, revenue_yoy_pct: -18.5, revenue_qoq_pct: -9.7,
    net_profit_cr: -12.4, net_profit_yoy_pct: -244.2, net_profit_qoq_pct: -180.5,
    net_profit_swing: "profit->loss",
    ebitda_cr: 21.8, ebitda_yoy_pct: -62.1, ebitda_qoq_pct: -44.9,
    ebitda_margin_pct: 3.56, ebitda_margin_yoy_pct: 7.66, ebitda_margin_qoq_pct: 5.83,
    revenue_cur_cr: 612.4, revenue_prevq_cr: 678.2, revenue_yrago_cr: 751.4,
    net_profit_cur_cr: -12.4, net_profit_prevq_cr: 15.4, net_profit_yrago_cr: 8.6,
    ebitda_cur_cr: 21.8, ebitda_prevq_cr: 39.6, ebitda_yrago_cr: 57.5,
    dedup_key: "MOCK0006|standalone",
    filed_at: "2026-07-27T15:48:00",
    extraction_confidence: 0.9,
    headline: "Financial Results for the Quarter ended June 30, 2026",
  }),
  mk({
    company_name: "GreenLeaf Consumer Products Ltd",
    bse_scrip_code: "500825",
    nse_symbol: "GREENLEAF",
    result_type: "standalone",
    revenue_cr: 388.9, revenue_yoy_pct: 6.2, revenue_qoq_pct: 1.4,
    net_profit_cr: 41.7, net_profit_yoy_pct: 8.1, net_profit_qoq_pct: 0.9,
    ebitda_cr: 66.3, ebitda_yoy_pct: 7.0, ebitda_qoq_pct: 1.1,
    ebitda_margin_pct: 17.05, ebitda_margin_yoy_pct: 16.92, ebitda_margin_qoq_pct: 17.10,
    revenue_cur_cr: 388.9, revenue_prevq_cr: 383.5, revenue_yrago_cr: 366.2,
    net_profit_cur_cr: 41.7, net_profit_prevq_cr: 41.3, net_profit_yrago_cr: 38.6,
    ebitda_cur_cr: 66.3, ebitda_prevq_cr: 65.6, ebitda_yrago_cr: 61.9,
    dedup_key: "MOCK0007|standalone",
    filed_at: "2026-07-26T20:02:00",
    headline: "Financial Results for the Quarter ended June 30, 2026",
  }),
  mk({
    company_name: "Coastal Logistics & Ports Ltd",
    bse_scrip_code: "532788",
    nse_symbol: "COASTALLOG",
    result_type: "consolidated",
    quarter_label: "Q4 FY26",
    period_end: "2026-03-31",
    prev_quarter_end: "2025-12-31",
    year_ago_quarter_end: "2025-03-31",
    revenue_cr: 259.3, revenue_yoy_pct: 15.9, revenue_qoq_pct: 6.7,
    net_profit_cr: 33.8, net_profit_yoy_pct: 22.5, net_profit_qoq_pct: -4.1,
    ebitda_cr: 71.6, ebitda_yoy_pct: 19.4, ebitda_qoq_pct: 3.2,
    ebitda_margin_pct: 27.61, ebitda_margin_yoy_pct: 26.79, ebitda_margin_qoq_pct: 28.53,
    revenue_cur_cr: 259.3, revenue_prevq_cr: 243.0, revenue_yrago_cr: 223.7,
    net_profit_cur_cr: 33.8, net_profit_prevq_cr: 35.2, net_profit_yrago_cr: 27.6,
    ebitda_cur_cr: 71.6, ebitda_prevq_cr: 69.4, ebitda_yrago_cr: 59.9,
    dedup_key: "MOCK0008|consolidated",
    filed_at: "2026-07-26T14:20:00",
    headline: "Audited Consolidated Financial Results for the year and quarter ended March 31, 2026",
  }),
];
